import type { AppCatalogItem } from '@/components/gallery/app-card';

export const MOCK_APPS: AppCatalogItem[] = [
  { id: '1',  app_name: 'sales_dashboard',      display_name: 'Sales Dashboard',        icon_emoji: '📊', app_version: '2.1', app_status: 'READY', app_comment: 'Real-time sales metrics and KPI tracking',         category: 'Analytics',  is_visible: true, sort_order: 1,  last_synced_at: null, compute_pool: 'POOL_BUSINESS_APPS', service_name: null, postgres_instance: 'pg_business', endpoint_url: null, gallery_compatible: false },
  { id: '2',  app_name: 'inventory_tracker',     display_name: 'Inventory Tracker',      icon_emoji: '📦', app_version: '1.4', app_status: 'READY', app_comment: 'Warehouse inventory monitoring system',            category: 'Operations', is_visible: true, sort_order: 2,  last_synced_at: null, compute_pool: 'POOL_BUSINESS_APPS', service_name: null, postgres_instance: 'pg_business', endpoint_url: null, gallery_compatible: false },
  { id: '3',  app_name: 'churn_predictor',       display_name: 'Churn Predictor',        icon_emoji: '🤖', app_version: '3.0', app_status: 'READY', app_comment: 'ML-powered customer churn prediction',            category: 'AI/ML',      is_visible: true, sort_order: 3,  last_synced_at: null, compute_pool: 'POOL_ML',            service_name: null, postgres_instance: 'pg_ml', endpoint_url: null, gallery_compatible: false },
  { id: '4',  app_name: 'cost_optimizer',        display_name: 'Cost Optimizer',         icon_emoji: '💰', app_version: '1.2', app_status: 'READY', app_comment: 'Snowflake credit usage analysis and optimization', category: 'Analytics',  is_visible: true, sort_order: 4,  last_synced_at: null, compute_pool: 'POOL_BUSINESS_APPS', service_name: null, postgres_instance: 'pg_business', endpoint_url: null, gallery_compatible: false },
  { id: '5',  app_name: 'data_quality_monitor',  display_name: 'Data Quality Monitor',   icon_emoji: '🔍', app_version: '2.0', app_status: 'READY', app_comment: 'Automated data quality checks and alerts',        category: 'Governance', is_visible: true, sort_order: 5,  last_synced_at: null, compute_pool: 'POOL_PLATFORM',      service_name: null, postgres_instance: 'pg_platform', endpoint_url: null, gallery_compatible: false },
  { id: '6',  app_name: 'llm_chatbot',           display_name: 'LLM Chatbot',            icon_emoji: '💬', app_version: '1.0', app_status: 'READY', app_comment: 'Cortex AI-powered conversational assistant',      category: 'AI/ML',      is_visible: true, sort_order: 6,  last_synced_at: null, compute_pool: 'POOL_ML',            service_name: null, postgres_instance: 'pg_ml', endpoint_url: null, gallery_compatible: false },
  { id: '7',  app_name: 'anomaly_detector',      display_name: 'Anomaly Detector',       icon_emoji: '⚠️', app_version: '1.1', app_status: 'READY', app_comment: 'Time-series anomaly detection for metrics',       category: 'AI/ML',      is_visible: true, sort_order: 7,  last_synced_at: null, compute_pool: 'POOL_ML',            service_name: null, postgres_instance: 'pg_ml', endpoint_url: null, gallery_compatible: false },
  { id: '8',  app_name: 'report_builder',        display_name: 'Report Builder',         icon_emoji: '📝', app_version: '2.3', app_status: 'READY', app_comment: 'Drag-and-drop report creation tool',              category: 'Analytics',  is_visible: true, sort_order: 8,  last_synced_at: null, compute_pool: 'POOL_BUSINESS_APPS', service_name: null, postgres_instance: 'pg_business', endpoint_url: null, gallery_compatible: false },
  { id: '9',  app_name: 'etl_pipeline_mgr',      display_name: 'ETL Pipeline Manager',   icon_emoji: '🔄', app_version: '3.1', app_status: 'READY', app_comment: 'Visual ETL pipeline orchestration',               category: 'Operations', is_visible: true, sort_order: 9,  last_synced_at: null, compute_pool: 'POOL_PLATFORM',      service_name: null, postgres_instance: 'pg_tools', endpoint_url: null, gallery_compatible: false },
  { id: '10', app_name: 'customer_360',          display_name: 'Customer 360',           icon_emoji: '👥', app_version: '1.5', app_status: 'READY', app_comment: 'Unified customer profile viewer',                 category: 'Analytics',  is_visible: true, sort_order: 10, last_synced_at: null, compute_pool: 'POOL_BUSINESS_APPS', service_name: null, postgres_instance: 'pg_business', endpoint_url: null, gallery_compatible: false },
  { id: '11', app_name: 'geo_analytics',         display_name: 'Geo Analytics',          icon_emoji: '🌐', app_version: '1.0', app_status: 'READY', app_comment: 'Location-based analytics and mapping',            category: 'Analytics',  is_visible: true, sort_order: 11, last_synced_at: null, compute_pool: 'POOL_PLATFORM',      service_name: null, postgres_instance: 'pg_tools', endpoint_url: null, gallery_compatible: false },
  { id: '12', app_name: 'notebook_env',          display_name: 'Notebook Environment',   icon_emoji: '🧪', app_version: '2.0', app_status: 'READY', app_comment: 'Jupyter-compatible notebook workspace',           category: 'Tools',      is_visible: true, sort_order: 12, last_synced_at: null, compute_pool: 'POOL_PLATFORM',      service_name: null, postgres_instance: 'pg_tools', endpoint_url: null, gallery_compatible: false },
  { id: '13', app_name: 'sentiment_analyzer',    display_name: 'Sentiment Analyzer',     icon_emoji: '😊', app_version: '1.3', app_status: 'READY', app_comment: 'NLP sentiment analysis on text data',             category: 'AI/ML',      is_visible: true, sort_order: 13, last_synced_at: null, compute_pool: 'POOL_ML',            service_name: null, postgres_instance: 'pg_ml', endpoint_url: null, gallery_compatible: false },
  { id: '14', app_name: 'access_governance',     display_name: 'Access Governance',      icon_emoji: '🛡', app_version: '1.0', app_status: 'READY', app_comment: 'Role and permission audit dashboard',             category: 'Governance', is_visible: true, sort_order: 14, last_synced_at: null, compute_pool: 'POOL_PLATFORM',      service_name: null, postgres_instance: 'pg_platform', endpoint_url: null, gallery_compatible: false },
  { id: '15', app_name: 'compute_monitor',       display_name: 'Compute Monitor',        icon_emoji: '🖥', app_version: '1.2', app_status: 'READY', app_comment: 'SPCS compute pool monitoring and alerting',       category: 'Operations', is_visible: true, sort_order: 15, last_synced_at: null, compute_pool: 'POOL_PLATFORM',      service_name: null, postgres_instance: 'pg_tools', endpoint_url: null, gallery_compatible: false },
  { id: '16', app_name: 'forecast_engine',       display_name: 'Forecast Engine',        icon_emoji: '📈', app_version: '2.1', app_status: 'READY', app_comment: 'Time-series forecasting with Cortex ML',         category: 'AI/ML',      is_visible: true, sort_order: 16, last_synced_at: null, compute_pool: 'POOL_ML',            service_name: null, postgres_instance: 'pg_ml', endpoint_url: null, gallery_compatible: false },
  { id: '17', app_name: 'sql_workspace',         display_name: 'SQL Workspace',          icon_emoji: '⚡', app_version: '1.0', app_status: 'READY', app_comment: 'Interactive SQL editor and query runner',         category: 'Tools',      is_visible: true, sort_order: 17, last_synced_at: null, compute_pool: 'POOL_PLATFORM',      service_name: null, postgres_instance: 'pg_tools', endpoint_url: null, gallery_compatible: false },
  { id: '18', app_name: 'data_catalog_browser',  display_name: 'Data Catalog Browser',   icon_emoji: '🗂', app_version: '1.1', app_status: 'READY', app_comment: 'Browse and search data assets across accounts',   category: 'Governance', is_visible: true, sort_order: 18, last_synced_at: null, compute_pool: 'POOL_PLATFORM',      service_name: null, postgres_instance: 'pg_platform', endpoint_url: null, gallery_compatible: false },
];

// Demo: pools treated as running when no real leases exist
export const MOCK_RUNNING_POOLS = new Set(['POOL_BUSINESS_APPS', 'POOL_ML']);

// Compute pool sizes (in production, this comes from Snowflake metadata)
export const POOL_SIZES: Record<string, string> = {
  POOL_BUSINESS_APPS: 'XS',
  POOL_ML: 'S',
  POOL_PLATFORM: 'XS',
};
